### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ViPeR5000** [InfotelGLPI/tasklists#15]
Fatal error: Uncaught exception 'Zend\I18n\Exception\ParseException' with message 'Unknown or invalid parser rule: nplurals=INTEGER; plural=EXPRESSION;' in /usr/share/glpi/vendor/zendframework/zend-i18n/src/Translator/Plural/Rule.php:194 Stack trace: #0 /usr/share/glpi/vendor/zendframework/zend-i18n/src/Translator/Loader/Gettext.php(149): Zend\I18n\Translator\Plural\Rule::fromString(' nplurals=INTEG...') #1 /usr/share/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php(747): Zend\I18n\Translator\Loader\Gettext->load('pt_PT', '/usr/share/glpi...') #2 /usr/share/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php(619): Zend\I18n\Translator\Translator->loadMessagesFromFiles('tasklists', 'pt_PT') #3 /usr/share/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php(442): Zend\I18n\Translator\Translator->loadMessages('tasklists', 'pt_PT') #4 /usr/share/glpi/vendor/zendframework/zend-i18n/src/Translator/Translator.php(356): Zend\I18n\Translator\Translator->getTranslatedMessage('Tasks list' in /usr/share/glpi/vendor/zendframework/zend-i18n/src/Translator/Plural/Rule.php on line 194

**Comment by keha35** [comment]
Hi, 

we need more informations to help you with this error :

Dear GLPi user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* Verify that your question has not already been asked
* Please use the below template.
* Delete this text before submiting your issue.

The Plugin team.

------------
* Version of the plugin : 


* Version of your GLPI : 


* Steps to reproduce (which actions have you made) :


* Expected result :


* Actual result :


* URL of the page :


* Screenshot of the problem (if pertinent) :

**Comment by arhipovdv** [comment]
Just copy tasklist plugin to GLPI plugins folder, then refresh plugin page - got HTTP ERROR 500 and error in apache log as in first message here.
glpi 9.4, ubuntu 18 LTS, PHP 7.3

**Comment by arhipovdv** [comment]
ok, i reproduce and found the same issue: https://github.com/InfotelGLPI/mydashboard/issues/6
if prefered language Fr - all ok, if  another then error

**Comment by keha35** [comment]
Which language did you use on GLPI?
I see "pt_PT" in the error but there is no Português traduction of the plugin.

**Comment by arhipovdv** [comment]
> Which language did you use on GLPI?
> I see "pt_PT" in the error but there is no Português traduction of the plugin.

English, in my last message: Zend\I18n\Translator\Loader\Gettext->load('en_GB', '/var/www/glpi/p...')

**Comment by keha35** [comment]
The release as been update.
Can you try with it ? (still 1.5.0)

**Comment by arhipovdv** [comment]
> The release as been update.
> Can you try with it ? (still 1.5.0)

All is ok now, works perfect!

**Comment by ViPeR5000** [comment]
works perfect!


> Which language did you use on GLPI?
> I see "pt_PT" in the error but there is no Português traduction of the plugin.

I translate it :)
[task_listpt_PT.zip](https://github.com/InfotelGLPI/tasklists/files/2905725/task_listpt_PT.zip)


With the new release it works perfect! Thks

**Comment by tsmr** [comment]
Thanks. We add it into transifex. You can help us : https://www.transifex.com/tsmr/GLPI_tasklists/

**Comment by ViPeR5000** [comment]
I see :)
