### ISSUE TITLE
You cannot archive a task with this state

### ISSUE THREAD

**Issue by pintasart** [InfotelGLPI/tasklists#18]
* Version of the plugin : 
glpi-tasklists.1.5.0

* Version of your GLPI : 
glpi-9.4.2

* Steps to reproduce (which actions have you made) :
Put a task on last state  "Closed" and then edit task and make "archived" to yes

* Expected result :
Archive a closed task and hidden this task

* Actual result :
"You cannot archive a task with this state"

**Comment by no6una9a** [comment]
Same here - also interested for a solution about this!

**Comment by tsmr** [comment]
Into /plugins/tasklists/front/taskstate.php, your "Closed" status is tagged as Finished state ?

**Comment by pintasart** [comment]
No.  I changed it and works fine.
Ok.
