### ISSUE TITLE
GLPI tasks and tasklist

### ISSUE THREAD

**Issue by paulz1** [InfotelGLPI/tasklists#19]
* Version of the plugin : 1.5.0
* Version of your GLPI : 9.4.2

Just a little stupid question, but it does not seem evident.

Actually, there are a native "Tasks" in GLPI.
Do I understand correctly that there is no link between GLPI "Tasks" and Tasklist ?
These are two different type of objects?

For example, while processing a ticket, I could create a task. But this task is not present in tasklist (and I do not see any possibility to add this task to my tasklist).
I also could create a task in my tasklist, when I could link this task to some ticket. But this task is not shown in ticket processing (I could see it in Linked tasks).

If I am right, it's not an issue by itself. But I think it should be mentioned in plugin description. Without this mention the situation is a little bit confused.

Thank you for your help (and for wonderful plugin as well :-)).

P.S.: At the same time, may be these two kind of tasks should be merged?

**Comment by gguib** [comment]
Hi, there's no stupid question ! Obviously, we can feel confused about that. 
Task from tasklist are related to IT projects in general while others are related to tickets follow-up, and natively managed by the core of glpi. So, there's no links between them and infortunately no mergeable. At least  new plugin could bring that feature.

hope it helps ! 
Regards,
Guillaume

**Comment by paulz1** [comment]
>Dec 31, 2019
Beautiful date! :-)

Sorry, I did not monitor this issue, so I saw your reply only today.
Thank you for explanations. It's more clear now.

I think we could close this ticket.
