### ISSUE TITLE
Task List permission error

### ISSUE THREAD

**Issue by Fluffycockroach** [InfotelGLPI/tasklists#20]
Dear GLPi user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* Verify that your question has not already been asked
* Please use the below template.
* Delete this text before submiting your issue.

The Plugin team.

------------
* Version of the plugin : 1.5.0

* Version of your GLPI : 9.4.2

* Steps to reproduce (which actions have you made) : Have installed the add-in. Then completely removed and re-downloaded again and re-installed. 

* Expected result : Open Tasks List and start using

* Actual result : Selecting Tasks List from Assistance tab in GLPI, get the following error : You don't have the right to see any context

* URL of the page :

* Screenshot of the problem (if pertinent) : 
<img width="1278" alt="GLPI Tasks List error" src="https://user-images.githubusercontent.com/53526972/62217115-f8653680-b3a1-11e9-8e66-0988ef60c1e7.PNG">

**Comment by ales-infotel** [comment]
Hello,
You have to create at least one context in  : Setup > Dropdowns > Tasks list > Contexts.
After you have to create Statuses and for each status select one context  or more.

**Comment by Fluffycockroach** [comment]
That's it!!! Thank you soooo much! In all the searching I have done I never came across this and would never even have though of looking there.
