### ISSUE TITLE
Task List Menu Preference Not Show In Profile

### ISSUE THREAD

**Issue by fadlirifai** [InfotelGLPI/tasklists#22]
The Plugin team.

------------
* Version of the plugin : 1.5.0

* Version of your GLPI : GLPI 9.4.3 

* Steps to reproduce (which actions have you made) : Download tar.gz

* Expected result : Can Add Task List Menu Preference - In Observer Profile, so we can set user to observe the task list

* Actual result : only Admin can see the task list

* URL of the page : 

* Screenshot of the problem (if pertinent) :
![DeepinScreenshot_20190926074754](https://user-images.githubusercontent.com/47996454/65649746-0d70e580-e032-11e9-9507-f6d6d0becc90.png)
![Selection_121](https://user-images.githubusercontent.com/47996454/65649756-195ca780-e032-11e9-847a-4c334a4a74a0.png)

**Comment by tsmr** [comment]
You must give right to the plugin to the observer profile
