### ISSUE TITLE
Only Super-Admin see Task List Menu

### ISSUE THREAD

**Issue by HiopsNerevar** [InfotelGLPI/tasklists#24]
* Version of the plugin :  1.5.0
* Version of your GLPI : 9.4.4
* Steps to reproduce (which actions have you made) : Just install plugin and create Contexts
* Expected result : All users see TaskList menu item on main menu
* Actual result : Menu item sees only Super Admin

**Comment by stephencamilo** [comment]
I am getting the same issue here.

**Comment by tsmr** [comment]
Have you setup rights into user profile ?

**Comment by stephencamilo** [comment]
> Have you setup rights into user profile ?

Now I got the right setup working, but a instruction manual would be great to avoid the user to quit using the plugin, most beginners as I am, would do so.

**Comment by tsmr** [comment]
https://github.com/InfotelGLPI/tasklists/wiki
