### ISSUE TITLE
Mise à jour du plugin 1.5.0 vers 1.5.1

### ISSUE THREAD

**Issue by jorispegli** [InfotelGLPI/tasklists#28]
Bonjour, 
j'utilise actuellement GLPi 9.4.5 et le plugin tasklists 1.5.0. J'ai mis à jour ce dernier en version 1.5.1 (suppression du dossier tasklists, désarchivage du nouveau et réinstallation depuis GLPi). Mais lorsque je vais dans l'interface Liste des tâches, plus rien ne s'affiche. En faisant marche arrière et v1.5.0, tout est redevenu normal.
Merci pour votre aide.
JP

**Comment by tsmr** [comment]
Avez-vous essayé de vider votre cache ? nous avons mis à jour la librairie utilisée

**Comment by jorispegli** [comment]
Merci, réinstall + cache vidé, cela fonctionne parfaitement. Merci
