### ISSUE TITLE
Setup notifications

### ISSUE THREAD

**Issue by Bi0haz4** [InfotelGLPI/tasklists#29]
* Version of the plugin : 1.5.0

* Version of your GLPI : 9.4.5

* Steps to reproduce (which actions have you made) : I would like to setup notifications but in "Configuration -> Notifications -> Notifications" I can't find any notification related to the Tasklists plugin. The Wiki does not help.

* Expected result : Receive an email when an update is made to a task, or a new task is created.

* Actual result : Can't setup notifications

* URL of the page : http://glpi.contoso.local/front/notification.php

* Screenshot of the problem (if pertinent) :

**Comment by tsmr** [comment]
Problim on install. Please try install the 1.5.1 version
