### ISSUE TITLE
Rights work incorrect

### ISSUE THREAD

**Issue by kRaVeda** [InfotelGLPI/tasklists#3]
Hello,

Everybody can see all tasks and change them even if visibility is set to "This user" or "This user and this group".
Can you fix it? Thank You.

**Comment by tsmr** [comment]
In fact, the visibility field is to filter mydashboard widget view (http://blogglpi.infotel.com/une-creation-infotel-le-plugin-my-dashboard/), not for filter the task lists into helpdesk menu

**Comment by kRaVeda** [comment]
I've understood, thank You!
