### ISSUE TITLE
Définition des status et menu pour affichage Kanban

### ISSUE THREAD

**Issue by tfageo18** [InfotelGLPI/tasklists#30]
Problème 1 : 
* Version of the plugin : 1.1.0

* Version of your GLPI : 9.1.6

* Steps to reproduce (which actions have you made) : Aller dans Configuration -> Intitulé -> Liste des tâches

* Expected result : Ajouter un status

* Actual result : Pas de menu Ajouter un statys

* Screenshot of the problem (if pertinent) :
![image](https://user-images.githubusercontent.com/6224189/79469763-e21b0b80-8000-11ea-8dd1-94830338ad9e.png)

Problème 2 : URL pour accéder à la vue Kanban

**Comment by tsmr** [comment]
so old version (problem on install i think)
