### ISSUE TITLE
 TaskList plugin is not displayed on a profile other than "superadmin"

### ISSUE THREAD

**Issue by roniweb26** [InfotelGLPI/tasklists#31]
* Plugin version: 1.4.2

* Version of your GLPI: 9.3.4

* Steps to reproduce (what actions did you do): Technician profile access menu> Assistence> TaskList. This option is not displayed.

Displayed only on the "SuperAdmin" profile.

* Expected result: Find TaskList

* Current result: Can't find TaskList

I really need the Technician or Observer profile to have access.
How to make?

**Comment by stephencamilo** [comment]
I am getting the same issue here.

**Comment by tsmr** [comment]
https://github.com/InfotelGLPI/tasklists/wiki

Give rights to profile
