### ISSUE TITLE
tasklist ne fonctionne pas 

### ISSUE THREAD

**Issue by Gskill75** [InfotelGLPI/tasklists#36]
Dear GLPi user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* Verify that your question has not already been asked
* Please use the below template.
* Delete this text before submiting your issue.

The Plugin team.

------------
* Version of the plugin : 
1.6.0

* Version of your GLPI : 
9.5

* Steps to reproduce (which actions have you made) :
en super admin quan on clique sur + dans la listes des tâches

* Expected result :
erreur 404

* Actual result :

* URL of the page :
http://tickets2.lgb.loc/plugins/tasklists/front/setup.templates.php?add=1

* Screenshot of the problem (if pertinent) :
![glpi erreur](https://user-images.githubusercontent.com/45794145/88656768-1bb7e400-d0d1-11ea-824b-b948255bfb24.png)

**Comment by Dayflare** [comment]
i can confirm this error.
Can't create status or context too, there is no "Save" oder "Create" Button when trying to create a status.

![grafik](https://user-images.githubusercontent.com/42730126/88891798-0d3e0980-d244-11ea-94c0-d48074614ff1.png)

Tried to completely delete and reinstall the plugin from the marketplace. GLPI Version 9.5.0

**Comment by tsmr** [comment]
Hello
Can you try to install it without marketplace ?

**Comment by Gskill75** [comment]
Bonjour,
Je l'ai installé depuis le marketplace j'ai testé de le desinitalle et
réinstaller mais toujours pareil.

Le jeu. 30 juil. 2020 à 09:43, Xavier CAILLAUD <notifications@github.com> a
écrit :

**Comment by keha35** [comment]
Hi,

We have remove the plugin from the marketplace it will be add for the next release.
Please install it without marketplace.
