### ISSUE TITLE
 Error creating contexts

### ISSUE THREAD

**Issue by pamartinez666** [InfotelGLPI/tasklists#38]
------------
* Version of the plugin : 1.6.0

* Version of your GLPI : 9.5.1

* Steps to reproduce (which actions have you made) :
Setup > Dropdowns > Tasklists > Contexts
Add

* Expected result :
add new contexts

* Actual result :
there is no button to save

* URL of the page :
Is local

* Screenshot of the problem (if pertinent) :
![image](https://user-images.githubusercontent.com/69250549/91982169-3ac51980-ed00-11ea-92b2-cb3888ce72e4.png)

**Comment by keha35** [comment]
Hi,

Can you enable the debug mode ?
Then have you some errors on this page?

If not can you check the php_errors.log and the sql_errors.log files

**Comment by pamartinez666** [comment]
Hi,

Debug mode

![image](https://user-images.githubusercontent.com/69250549/91985643-e40d0f00-ed02-11ea-8f78-adc1bc6b1063.png)

**Comment by keha35** [comment]
it seems the plugin isn't correctly installed.
It was an update or the first install of the plugin?
If it's a fresh install can you uninstall and reinstall it ?

**Comment by pamartinez666** [comment]
It was a new installation.
I reinstalled but the error persists

**Comment by pamartinez666** [comment]
I reinstalled again and it was solved.
Thanks for the answers
