### ISSUE TITLE
Kanban on tickets, filters search only for text contained in the name

### ISSUE THREAD

**Issue by jorgecamargosdb** [InfotelGLPI/tasklists#48]
Hello,

We noticed that when using Kanban for calls or projects, when filtering by a group for example, it does not display the list of assigned Groups, performing the search only by the typed text.
In the case of groups whose prefix is the same, it is necessary to use the plus filter, to eliminate groups that do not want results, for example:

To search for an assigned group "System N1", where there are other groups such as System N2, System SAP, System Satellite... it is necessary to search:

group:System; group:N1
or
group:System; !group:N2; !group:Satellite

Is there any way to perform this search more directly?

------------
* Version of the plugin : 
Task List v2.0.1

* Version of your GLPI : 
GLPI 10.0.2

* Steps to reproduce (which actions have you made) :
Assign tickets and/or projects to different groups with the same prefix. (N1 Support, N2 Support, SAP Support, Totvs Support, N1 Systems, N2 Systems, SAP Systems, SAP Registration, Totvs Registration)
Search for calls in Kanban Global and filter the calls assigned to a group, for example Totvs Support.

* Expected result :
A quick and accurate filter selecting the exact group you want result

* Actual result :
Need to include multiple filters to exclude possibilities of equal or partial names

* Screenshot of the problem (if pertinent) :
![Filtro Kanban_03](https://user-images.githubusercontent.com/23311692/183678302-a1fddeec-329d-4a79-9665-07c6a3bd64ae.png)
![Filtro Kanban_02](https://user-images.githubusercontent.com/23311692/183678306-ac6a6249-7313-4a31-91cd-6d21899dca0c.png)
![Filtro Kanban_01](https://user-images.githubusercontent.com/23311692/183678308-1206c29a-bef7-4d8d-b2b7-ed932a87f221.png)

**Comment by jorgecamargosdb** [comment]
Thanks for the feedback

That filter with "N1 Systems" didn't work
![image](https://user-images.githubusercontent.com/23311692/183685534-9eafd914-c53c-4b97-8d24-13b3e6085929.png)
![image](https://user-images.githubusercontent.com/23311692/183685618-676615cd-cb80-4fa7-91ea-59d868d1c4b0.png)

**Comment by cconard96** [comment]
Hello,
Can you test the fix in glpi-project/glpi#12426?
The fix in the core should apply to this plugin too as it seems to use the same tokenized search code.
You may need to clear your browser cache after making the changes done in the patch.
