### ISSUE TITLE
Transifex - missing charset definition in header of file cs_CZ.po

### ISSUE THREAD

**Issue by p-bo** [InfotelGLPI/tasklists#5]
In file cs_CZ.po
(wrong settings on Transifex)

is
"Content-Type: text/plain; charset=CHARSET\n"

which leads to error in conversion to .mo :

msgfmt for_use_GLPI_tasklists_glpipot_cs_CZ.po -o for_use_GLPI_tasklists_glpipot_cs_CZ.po.mo

ffor_use_GLPI_tasklists_glpipot_cs_CZ.po: warning: Charset "CHARSET" is not a portable encoding name. Message conversion to user's charset might not work.

record should be:
"Content-Type: text/plain; charset=UTF8\n"

Thanks :)

**Comment by amma35** [comment]
We cannot modify the charset, you must check before compiling in.mo and modify by hand if necessary. 
We haven't found a solution yet.

I add the files cs_CZ.po and cs_CZ.mo to the plugin.

**Comment by gnehad** [comment]
The charser should be "Content-Type: text/plain; charset=UTF-8\n"
it's UTF-8 rather than UTF8
