### ISSUE TITLE
[GLPI 10.0.3] [ tasklists 2.0.1] Description field stay empty

### ISSUE THREAD

**Issue by michaelNFF** [InfotelGLPI/tasklists#50]
Description field stay empty

------------
* Version of the plugin :  tasklists 2.0.1

* Version of your GLPI : GLPI 10.0.3

* Steps to reproduce (which actions have you made) : Create or modify task

**Comment by michaelNFF** [comment]
Debug mode 

PHP Notice (8): Undefined index: content in /var/www/html/glpi/marketplace/tasklists/inc/task.class.php at line 644

**Comment by michaelNFF** [comment]
Could you check database name field description.

Some time pages search BDD field "comment" and some time "content"

SQL Error "1054": Unknown column 'glpi_plugin_tasklists_tasks.comment' in 'field list

**Comment by michaelNFF** [comment]
Upgrade GLPI to 10.0.3 today

**Comment by tsmr** [comment]
ALTER TABLE `glpi_plugin_tasklists_tasks`
    CHANGE `comment` `content` text collate utf8mb4_unicode_ci;

**Comment by michaelNFF** [comment]
Is solved with this fix.

Thanks
