### ISSUE TITLE
Only one Status  - backlog 

### ISSUE THREAD

**Issue by dzinksol-oss** [InfotelGLPI/tasklists#57]
Hello supporters :-) 

------------
* Version of the plugin : 

2.0.3

* Version of your GLPI : 

10.0.16

* Steps to reproduce (which actions have you made) :

Move task by mouse to diffirent status - diffirent then Backlog. 

* Expected result :

I can select in desciption any status to save. 

* Actual result :

I can move task to diffirent status by mouse and it stay there where I set. But when I enter to change in detail + save, it set me back to backlog, becouse only status - Backlog.

* URL of the page :

* Screenshot of the problem (if pertinent) :

![image](https://github.com/user-attachments/assets/ab8ae07a-a1cd-48b3-bff2-cd80ea727a76)

![image](https://github.com/user-attachments/assets/29da5b6f-4741-4b8a-9e72-df4c413c40f7)

![image](https://github.com/user-attachments/assets/9b293986-9fb9-4186-b3a3-4d504478e4c7)

**Comment by dzinksol** [comment]
I was my fault of settings I do not added context to statuses:

![obraz](https://github.com/user-attachments/assets/577afa0f-bfd5-4474-af00-3f514569f2bb)
