### ISSUE TITLE
task list

### ISSUE THREAD

**Issue by DanieleSAN** [InfotelGLPI/tasklists#6]
Hi

I've just installed the plugin on glpi

I don't see the tasks with the "action" column. why?
![cattura](https://user-images.githubusercontent.com/30930714/39531058-9f9482dc-4e2a-11e8-9107-569765a6fb86.JPG)

**Comment by amma35** [comment]
Hi,

There is no action field in the task list.
What information are you talking about?

**Comment by DanieleSAN** [comment]
I saw it in the plugin's page on 

http://plugins.glpi-project.org/#/plugin/tasklists

**Comment by amma35** [comment]
The action column is not in the plugin itself, it is the display of a widget of the mydashboard plugin, it allows to pass the task to the status "Done".

**Comment by DanieleSAN** [comment]
Ah, ok thanks

sorry but I'm a newbie of glpi

bye bye



2018-05-02 17:29 GMT+02:00 Amandine Manceau <notifications@github.com>:
