### ISSUE TITLE
A way to set the rights on tasks

### ISSUE THREAD

**Issue by Mexonizator** [InfotelGLPI/tasklists#9]
Hello!

Is there a way to set who may see one's tasks and who may not? I mean not in the dashboard or something, but entirely, like, you know, is expected when you see the visibility field.

To be honest, all the usefullness of the plugin is almost killed by the fact that users can't hide their own tasks, and they all get mixed.

Thanks.

**Comment by tsmr** [comment]
In your profile you can define if you can see tasks of all users or not.
You can add visibility of context by groups
